"""empty message

Revision ID: c92d6f80244e
Revises: 18e790856b53
Create Date: 2019-03-15 18:45:27.432593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92d6f80244e'
down_revision = '18e790856b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classification')
    op.drop_table('build')
    op.create_index(op.f('ix_records_build'), 'records', ['build'], unique=False)
    op.create_index(op.f('ix_records_classification'), 'records', ['classification'], unique=False)
    op.create_index(op.f('ix_records_external'), 'records', ['external'], unique=False)
    op.create_index(op.f('ix_records_machine_id'), 'records', ['machine_id'], unique=False)
    op.create_index(op.f('ix_records_severity'), 'records', ['severity'], unique=False)
    op.create_index(op.f('ix_records_timestamp_server'), 'records', ['timestamp_server'], unique=False)
    op.drop_constraint('records_build_id_fkey', 'records', type_='foreignkey')
    op.drop_constraint('records_classification_id_fkey', 'records', type_='foreignkey')
    op.drop_column('records', 'backtrace')
    op.drop_column('records', 'build_id')
    op.drop_column('records', 'classification_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('classification_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('build_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('records', sa.Column('backtrace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('records_classification_id_fkey', 'records', 'classification', ['classification_id'], ['id'])
    op.create_foreign_key('records_build_id_fkey', 'records', 'build', ['build_id'], ['id'])
    op.drop_index(op.f('ix_records_timestamp_server'), table_name='records')
    op.drop_index(op.f('ix_records_severity'), table_name='records')
    op.drop_index(op.f('ix_records_machine_id'), table_name='records')
    op.drop_index(op.f('ix_records_external'), table_name='records')
    op.drop_index(op.f('ix_records_classification'), table_name='records')
    op.drop_index(op.f('ix_records_build'), table_name='records')
    op.create_table('build',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('build', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='build_pkey')
    )
    op.create_table('classification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('probe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classification_pkey')
    )
    # ### end Alembic commands ###
