version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
       POSTGRES_DB: telemetry
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
  app:
    build:
       context: ${PWD}
       dockerfile: ./docker/Dockerfile
    environment:
       FLASK_APP: /var/www/telemetry/telemetryui/run.py
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ${PWD}:/var/www/telemetry
    command: /usr/bin/bash /var/www/telemetry/docker/entrypoint.sh
