# Copyright © 2019 Intel Corporation
#
# SPDX-License-Identifier: GPL-3.0-only
version: '3.1'
services:
  redis:
    image: redis:5.0.5
  collector:
    ports:
       - 5001:5001
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_HOST: db
  webapp:
    depends_on:
       - redis
    ports:
       - 5000:5000
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_HOST: db
       REDIS_HOST: redis
